#!/bin/bash

# Get macOS version and architecture and compare it as number(e.g., 12.4 -> 1204). 12.4 is the first version witout python2.
version=$(sw_vers -productVersion)
arch=$(uname -m)
ver_major=$(echo "$version" | cut -d '.' -f1)
ver_minor=$(echo "$version" | cut -d '.' -f2)
ver_number=$((10#$ver_major * 100 + 10#${ver_minor:-0}))
if [ "$ver_number" -ge 1204 ]; then
if [ "$arch" = "arm64" ]; then
#ARM START has python3 only on ARM
echo "Apple Silicon (arm64)"

#ARM END
elif [ "$arch" = "x86_64" ]; then
#X86 START has python3 only on x86
echo "Intel (x86_64)"

#x86 END
fi
fi
